version: '3'

services:
    mysql:
        ports:
            - "3306:3306"
        image: "mysql:5.7.20"
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        ports:
            - "6379:6379"
        image: "redis:4.0.2"
