<?php

const APP_OK = 0;
const APP_ERR_GENERAL = 1;
const APP_ERR_ORDER_ALREADY_EXECUTED = 2;
const APP_ERR_BAD_ORDER = 3;

const APP_ERR_BAD_ORDER_NAME = 10;
const APP_ERR_BAD_ORDER_PRICE = 11;
const APP_ERR_BAD_ORDER_DESC = 12;

const APP_ERR_BAD_USER = 30;
const APP_ERR_BAD_CREDENTIALS = 31;
const APP_ERR_BAD_USERNAME = 32;
const APP_ERR_BAD_PASSWORD = 33;
const APP_ERR_BAD_PERMISSIONS = 34;
const APP_ERR_USERNAME_REGISTERED = 35;

const APP_ERR_USER_CANT_EXECUTE_ORDER = 50;
const APP_ERR_USER_CANT_CREATE_ORDER = 51;